# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

def location_info
  {:search_time=>"00.033468",
   :num_results=>1,
   :result=>
    {:Q1RQNVdbXlpEVA=>
      {:national=>false,
       :updated=>"2018-01-06T22:58:35",
       :postal_code=>"80223",
       :location_type_id=>0,
       :municipal=>false,
       :city=>"Denver",
       :event_only=>false,
       :latitude=>39.6934847226322,
       :province=>"CO",
       :fax=>"",
       :description=>"SustainAbility Recycling",
       :curbside=>false,
       :hours=>"Tuesday to Thursday: 10am - 6pm; Friday to Sunday: 9am - 3pm",
       :phone=>"303-424-1719",
       :address=>"1270 S. Bannock St",
       :notes_public=>"Please visit the website for fee information.",
       :created=>"2018-01-06T22:56:08",
       :url=>"https://www.sustainability-recycling.com/",
       :country=>"US",
       :region=>"Denver",
       :longitude=>-104.9898749995828,
       :geocoded=>false,
       :materials=>
        [{:dropoff=>true, :description=>"Alkaline Batteries", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>104, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Audio Equipment", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>485, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Blu-Ray Players", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>647, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Boomboxes", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>643, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Cables", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>481, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Car Batteries", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>4, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Cell Phones", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>245, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Computer Peripherals - External", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>483, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Computer Peripherals - Internal", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>615, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"CRT Computer Monitors", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>486, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"CRT Televisions", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>487, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Desktop Computers", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>85, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Digital Cameras", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>488, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"DVD Players", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>645, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Electronic Servers", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>340, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Game Consoles", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>332, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"GPS Systems", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>489, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Hard Drives", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>581, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Laptop Computers", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>491, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"LCD Computer Monitors", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>259, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"LCD Televisions", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>229, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Lithium-ion Batteries", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>6, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Microwaves", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>493, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Nickel-cadmium Batteries", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>126, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Nickel-metal Hydride Batteries", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>685, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Office Machines", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>272, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Power Tools", :business=>false, :url=>"", :residential=>true, :notes=>"Electric tools only, no tools that require gas.", :residential_method=>"dropoff", :business_method=>"none", :material_id=>577, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Printers", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>495, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Receivers", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>496, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Scanners", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>545, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Tablets", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>497, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"Toasters", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>549, :pickup=>false, :pending=>"F"},
         {:dropoff=>true, :description=>"VCRs", :business=>false, :url=>"", :residential=>true, :notes=>"", :residential_method=>"dropoff", :business_method=>"none", :material_id=>492, :pickup=>false, :pending=>"F"}],
       :notes=>"Please visit the website for fee information."}}}
end
